name: express_vet
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10

  # all dependencies
  cupertino_icons: ^1.0.8
  fluttertoast: ^9.0.0
  easy_localization: ^3.0.7+1
  get: ^4.7.2
  shared_preferences: ^2.5.2
  connectivity_plus:
  http: ^1.3.0
  device_info_plus: ^11.3.3
  timer_count_down: ^2.2.2
  webview_flutter: ^4.10.0
  webview_flutter_android:
  webview_flutter_wkwebview:
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  flutter_rounded_date_picker: ^3.0.4
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  location: ^8.0.0
  geocoding: ^3.0.0
  onesignal_flutter: ^5.3.4
  image_cropper: ^11.0.0
  smooth_page_indicator: ^1.2.1
  flutter_rating_bar: ^4.0.1
  app_links: ^6.4.0
  external_app_launcher: ^4.0.3
  flutter_inappwebview: ^6.1.5
  readmore: ^3.0.0
  flutter_font_icons: ^2.2.7
  dropdown_button2: ^2.3.9
  google_maps_flutter: ^2.11.0
  mobile_scanner: ^7.2.0
  flutter_flip_card: ^0.0.6
  date_format_field: ^0.1.0
  intl: ^0.20.2
  pin_code_fields: ^8.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  crypto: ^3.0.3
  flutter_image_compress: ^2.0.7
  image: ^4.0.17
  toastification: ^3.0.3
  sliding_up_panel:
  flutter_html:
  uuid: ^4.5.1
  widget_zoom: ^0.0.4
  permission_handler: ^11.3.1
  like_button: ^2.0.5
  vector_math: ^2.2.0
  web_socket_channel: ^3.0.1

  # component:
  #  git:
  #    url: https://github.com/SoLayZzzz/component.git
  #    ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4

flutter:
  assets:
    - assets/images/
    - assets/gif/
    - assets/fonts/
    - assets/icons/
    - assets/locale/

  uses-material-design: true

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
    - family: Battambang
      fonts:
        - asset: assets/fonts/Battambang.ttf



#  // Logo QA
#   static const String vet_logo_qa = 'assets/images/vet_logo_qa.jpg';
#   // Logo Production
#   static const String vet_logo = 'assets/images/vet_logo.png';

# Change logo command
# QA
# dart run flutter_launcher_icons -f flutter_launcher_icons-qa.yaml

# Production
# dart run flutter_launcher_icons -f flutter_launcher_icons-prod.yaml

# default command run
# flutter pub run flutter_launcher_icons

# Command to build app auto get qa or production

# build Apk
# flutter build apk --flavor qa --dart-define=FLAVOR=qa --release --target-platform=android-arm64 --analyze-size --tree-shake-icons
# flutter build apk --flavor prod --dart-define=FLAVOR=prod --release --target-platform=android-arm64 --analyze-size --tree-shake-icons

# iOS run
# flutter run --flavor qa --dart-define=FLAVOR=qa -d CA3A9594-78B6-4CF4-8DFC-BC3946601FDC
# flutter run --flavor prod --dart-define=FLAVOR=prod -d CA3A9594-78B6-4CF4-8DFC-BC3946601FDC

# android run
# flutter run -d emulator-5554 --flavor qa --dart-define=FLAVOR=qa
# flutter run -d emulator-5554 --flavor prod --dart-define=FLAVOR=prod
# flutter run -d DY4HE6PJOVIRAMHY --flavor prod --dart-define=FLAVOR=prod